# coding: utf-8

"""
    rokka.io

    digital image processing done right. [Documentation](https://rokka.io/documentation). [Changelog](https://api.rokka.io/changelog.md).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rokka_client_codegen
from rokka_client_codegen.api.stacks_api import StacksApi  # noqa: E501
from rokka_client_codegen.rest import ApiException


class TestStacksApi(unittest.TestCase):
    """StacksApi unit test stubs"""

    def setUp(self):
        self.api = rokka_client_codegen.api.stacks_api.StacksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_stack(self):
        """Test case for create_stack

        Create a new stack.  # noqa: E501
        """
        pass

    def test_delete_stack(self):
        """Test case for delete_stack

        Delete a stack.  # noqa: E501
        """
        pass

    def test_get_stack(self):
        """Test case for get_stack

        Get a single stack.  # noqa: E501
        """
        pass

    def test_list_operations(self):
        """Test case for list_operations

        Listing all available operations that can be used in stacks.  # noqa: E501
        """
        pass

    def test_list_stack_options(self):
        """Test case for list_stack_options

        List all available options that can be set on stacks.  # noqa: E501
        """
        pass

    def test_list_stacks(self):
        """Test case for list_stacks

        Get all stacks of an organization.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
