# coding: utf-8

"""
    rokka.io

    digital image processing done right. [Documentation](https://rokka.io/documentation). [Changelog](https://api.rokka.io/changelog.md).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rokka_client_codegen
from rokka_client_codegen.api.admin_api import AdminApi  # noqa: E501
from rokka_client_codegen.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = rokka_client_codegen.api.admin_api.AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_membership(self):
        """Test case for create_membership

        Add a rokka user into an organization.  # noqa: E501
        """
        pass

    def test_create_organization(self):
        """Test case for create_organization

        Register a new Organization.  # noqa: E501
        """
        pass

    def test_create_organization_options(self):
        """Test case for create_organization_options

        Update options for an organization.  # noqa: E501
        """
        pass

    def test_create_user(self):
        """Test case for create_user

        Register new user.  # noqa: E501
        """
        pass

    def test_delete_membership(self):
        """Test case for delete_membership

        Remove a user from an organization.  # noqa: E501
        """
        pass

    def test_get_membership(self):
        """Test case for get_membership

        Get information about organization membership of a rokka user.  # noqa: E501
        """
        pass

    def test_get_organization(self):
        """Test case for get_organization

        Get information about an organization.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
