# coding: utf-8

"""
    rokka.io

    digital image processing done right. [Documentation](https://rokka.io/documentation). [Changelog](https://api.rokka.io/changelog.md).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rokka_client_codegen
from rokka_client_codegen.models.membership import Membership  # noqa: E501
from rokka_client_codegen.rest import ApiException


class TestMembership(unittest.TestCase):
    """Membership unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMembership(self):
        """Test Membership"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rokka_client_codegen.models.membership.Membership()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
