# coding: utf-8

"""
    rokka.io

    digital image processing done right. [Documentation](https://rokka.io/documentation). [Changelog](https://api.rokka.io/changelog.md).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Membership(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'str',
        'organization_id': 'str',
        'role': 'str',
        'active': 'bool'
    }

    attribute_map = {
        'user_id': 'user_id',
        'organization_id': 'organization_id',
        'role': 'role',
        'active': 'active'
    }

    def __init__(self, user_id=None, organization_id=None, role=None, active=None):  # noqa: E501
        """Membership - a model defined in Swagger"""  # noqa: E501

        self._user_id = None
        self._organization_id = None
        self._role = None
        self._active = None
        self.discriminator = None

        if user_id is not None:
            self.user_id = user_id
        if organization_id is not None:
            self.organization_id = organization_id
        if role is not None:
            self.role = role
        if active is not None:
            self.active = active

    @property
    def user_id(self):
        """Gets the user_id of this Membership.  # noqa: E501


        :return: The user_id of this Membership.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Membership.


        :param user_id: The user_id of this Membership.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def organization_id(self):
        """Gets the organization_id of this Membership.  # noqa: E501


        :return: The organization_id of this Membership.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this Membership.


        :param organization_id: The organization_id of this Membership.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def role(self):
        """Gets the role of this Membership.  # noqa: E501


        :return: The role of this Membership.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this Membership.


        :param role: The role of this Membership.  # noqa: E501
        :type: str
        """

        self._role = role

    @property
    def active(self):
        """Gets the active of this Membership.  # noqa: E501


        :return: The active of this Membership.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this Membership.


        :param active: The active of this Membership.  # noqa: E501
        :type: bool
        """

        self._active = active

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Membership):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
