# coding: utf-8

"""
    rokka.io

    digital image processing done right. [Documentation](https://rokka.io/documentation). [Changelog](https://api.rokka.io/changelog.md).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from rokka_client_codegen.models.stack_expression import StackExpression  # noqa: F401,E501
from rokka_client_codegen.models.stack_operation import StackOperation  # noqa: F401,E501


class StackDefinition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stack_operations': 'list[StackOperation]',
        'stack_options': 'object',
        'stack_expressions': 'list[StackExpression]'
    }

    attribute_map = {
        'stack_operations': 'stack_operations',
        'stack_options': 'stack_options',
        'stack_expressions': 'stack_expressions'
    }

    def __init__(self, stack_operations=None, stack_options=None, stack_expressions=None):  # noqa: E501
        """StackDefinition - a model defined in Swagger"""  # noqa: E501

        self._stack_operations = None
        self._stack_options = None
        self._stack_expressions = None
        self.discriminator = None

        self.stack_operations = stack_operations
        if stack_options is not None:
            self.stack_options = stack_options
        if stack_expressions is not None:
            self.stack_expressions = stack_expressions

    @property
    def stack_operations(self):
        """Gets the stack_operations of this StackDefinition.  # noqa: E501

        Collection of stack operations  # noqa: E501

        :return: The stack_operations of this StackDefinition.  # noqa: E501
        :rtype: list[StackOperation]
        """
        return self._stack_operations

    @stack_operations.setter
    def stack_operations(self, stack_operations):
        """Sets the stack_operations of this StackDefinition.

        Collection of stack operations  # noqa: E501

        :param stack_operations: The stack_operations of this StackDefinition.  # noqa: E501
        :type: list[StackOperation]
        """
        if stack_operations is None:
            raise ValueError("Invalid value for `stack_operations`, must not be `None`")  # noqa: E501

        self._stack_operations = stack_operations

    @property
    def stack_options(self):
        """Gets the stack_options of this StackDefinition.  # noqa: E501


        :return: The stack_options of this StackDefinition.  # noqa: E501
        :rtype: object
        """
        return self._stack_options

    @stack_options.setter
    def stack_options(self, stack_options):
        """Sets the stack_options of this StackDefinition.


        :param stack_options: The stack_options of this StackDefinition.  # noqa: E501
        :type: object
        """

        self._stack_options = stack_options

    @property
    def stack_expressions(self):
        """Gets the stack_expressions of this StackDefinition.  # noqa: E501

        Collection of stack expressions  # noqa: E501

        :return: The stack_expressions of this StackDefinition.  # noqa: E501
        :rtype: list[StackExpression]
        """
        return self._stack_expressions

    @stack_expressions.setter
    def stack_expressions(self, stack_expressions):
        """Sets the stack_expressions of this StackDefinition.

        Collection of stack expressions  # noqa: E501

        :param stack_expressions: The stack_expressions of this StackDefinition.  # noqa: E501
        :type: list[StackExpression]
        """

        self._stack_expressions = stack_expressions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StackDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
